server:
  port: 8001

spring:
  application:
    name: houzhidaoadmin
  datasource:
      name: test
      url: jdbc:mysql://114.115.212.95:3306/houzhidao?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: WANGbowen0223!
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maxLifetime: 1800000
        maximumPoolSize: 15


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 10000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml
  type-aliases-package:
    - com.hippie.houzhidaoadmin.domain
